export const rivalTeams = [
  { id: "atl", name: "Atlanta Hawks", gm: "Darius Bell" },
  { id: "bos", name: "Boston Celtics", gm: "Elliot Walsh" },
  { id: "bkn", name: "Brooklyn Nets", gm: "Miles Abram" },
  { id: "cha", name: "Charlotte Hornets", gm: "Noah Whitaker" },
  { id: "chi", name: "Chicago Bulls", gm: "Grant Mercer" },
  { id: "cle", name: "Cleveland Cavaliers", gm: "Isaiah Cole" },
  { id: "dal", name: "Dallas Mavericks", gm: "Owen Strickland" },
  { id: "den", name: "Denver Nuggets", gm: "Calvin Price" },
  { id: "det", name: "Detroit Pistons", gm: "Marcus Vale" },
  { id: "gsw", name: "Golden State Warriors", gm: "Adrian Cross" },
  { id: "hou", name: "Houston Rockets", gm: "Victor Hayes" },
  { id: "ind", name: "Indiana Pacers", gm: "Simon Reed" },
  { id: "lac", name: "LA Clippers", gm: "Julian Pierce" },
  { id: "lal", name: "Los Angeles Lakers", gm: "Wesley Kane" },
  { id: "mem", name: "Memphis Grizzlies", gm: "Malcolm Brooks" },
  { id: "mia", name: "Miami Heat", gm: "Rafael Soto" },
  { id: "mil", name: "Milwaukee Bucks", gm: "Leonard Frost" },
  { id: "min", name: "Minnesota Timberwolves", gm: "Theo Ramsey" },
  { id: "nop", name: "New Orleans Pelicans", gm: "Bennett Shaw" },
  { id: "nyk", name: "New York Knicks", gm: "Dominic Hale" },
  { id: "okc", name: "Oklahoma City Thunder", gm: "Preston Lane" },
  { id: "orl", name: "Orlando Magic", gm: "Felix Ward" },
  { id: "phi", name: "Philadelphia 76ers", gm: "Jonah Bishop" },
  { id: "phx", name: "Phoenix Suns", gm: "Gideon Marks" },
  { id: "por", name: "Portland Trail Blazers", gm: "Evan Holt" },
  { id: "sac", name: "Sacramento Kings", gm: "Trevor Nash" },
  { id: "sas", name: "San Antonio Spurs", gm: "Nolan Voss" },
  { id: "tor", name: "Toronto Raptors", gm: "Arthur Quinn" },
  { id: "uta", name: "Utah Jazz", gm: "Silas Finch" },
  { id: "was", name: "Washington Wizards", gm: "Graham Lowell" },
] as const;

export const requestedPositions = ["PG", "SG", "SF", "PF", "C"] as const;
